[package]
name = "kersteg"
version = "0.1.0"
authors = ["Kersed <k3rs3d@pm.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rayon = "1.5.1"